//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rdb_scenarios {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Scripts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Scripts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("rdb_scenarios.Scripts", typeof(Scripts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TRIGGER t_checkAttributesLogger
        ///   ON  check_attributes
        ///   AFTER INSERT,DELETE,UPDATE
        ///AS 
        ///BEGIN
        ///	SET NOCOUNT ON;
        ///	DECLARE @event_type varchar(6)
        ///	IF EXISTS(SELECT * FROM inserted)
        ///		IF EXISTS(SELECT * FROM deleted)
        ///			SELECT @event_type = &apos;update&apos;
        ///		ELSE
        ///			SELECT @event_type = &apos;insert&apos;
        ///	ELSE
        ///	IF EXISTS(SELECT * FROM deleted)
        ///		SELECT @event_type = &apos;delete&apos;
        ///
        ///	DECLARE @table_name varchar(64)
        ///	SELECT
        ///		@table_name = OBJECT_NAME(parent_id)
        ///	FROM
        ///		sys.triggers
        ///	WHERE
        ///		object_id =  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string createLogTriggers {
            get {
                return ResourceManager.GetString("createLogTriggers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE [sp_connectScenario]
        ///  @selectedLanguage nvarchar(5)
        ///  AS
        ///  SELECT s.scenario_code, s.name, s.description, sa.type, sa.value, sa.language
        ///  FROM scenario s
        ///  LEFT JOIN scenario_contains sc ON s.scenario_code = sc.scenario_code
        ///  LEFT JOIN scenario_attributes sa ON sc.attribute_code = sa.attribute_code AND (sa.language = @selectedLanguage OR sa.language IS NULL)
        ///  RETURN
        ///GO
        ///
        ///CREATE PROCEDURE [sp_connectSection]
        ///  @selectedLanguage nvarchar(5)
        ///  AS
        ///  SELECT s.section_code, s.name [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string createProcedures {
            get {
                return ResourceManager.GetString("createProcedures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create table [operation]
        ///(
        ///	[operation_code] Integer Identity NOT NULL, UNIQUE ([operation_code]),
        ///	[name] Text NOT NULL,
        ///	[description] Text NOT NULL,
        ///Primary Key ([operation_code])
        ///) 
        ///go
        ///
        ///Create table [section]
        ///(
        ///	[section_code] Integer Identity NOT NULL, UNIQUE ([section_code]),
        ///	[name] Text NOT NULL,
        ///	[description] Text NOT NULL,
        ///Primary Key ([section_code])
        ///) 
        ///go
        ///
        ///Create table [scenario]
        ///(
        ///	[scenario_code] Integer Identity NOT NULL, UNIQUE ([scenario_code]),
        ///	[name] Text NOT NULL,        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string createTables {
            get {
                return ResourceManager.GetString("createTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TRIGGER t_checkAttributesValidation
        ///   ON  check_attributes
        ///   INSTEAD OF INSERT
        ///AS 
        ///BEGIN
        ///	SET NOCOUNT ON;
        ///	DECLARE @type NVarchar(20)
        ///	DECLARE @value bit
        ///	DECLARE @language NVarchar(5)
        ///	
        ///	SET @type = (SELECT type FROM inserted)
        ///	SET @language = (SELECT language FROM inserted)
        ///	SET @value = (SELECT DATALENGTH(value) FROM inserted)
        ///
        ///	if(DATALENGTH(@type) &gt; 0 and DATALENGTH(@value) &gt; 0)
        ///	begin
        ///		INSERT INTO check_attributes(type, value, language) VALUES(@type, (SELECT value FROM insert [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string createValidationTriggers {
            get {
                return ResourceManager.GetString("createValidationTriggers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop procedure sp_connectScenario
        ///go
        ///Drop procedure sp_connectSection
        ///go
        ///Drop procedure sp_connectCheck
        ///go
        ///Drop procedure sp_connectOperation
        ///go.
        /// </summary>
        internal static string dropProcedures {
            get {
                return ResourceManager.GetString("dropProcedures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop table [log] 
        ///go
        ///Drop table [scenario_checks] 
        ///go
        ///Drop table [scenario_contains] 
        ///go
        ///Drop table [section_contains] 
        ///go
        ///Drop table [check_contains] 
        ///go
        ///Drop table [scenario_attributes] 
        ///go
        ///Drop table [section_attributes] 
        ///go
        ///Drop table [check_attributes] 
        ///go
        ///Drop table [operation_contains] 
        ///go
        ///Drop table [operation_attributes] 
        ///go
        ///Drop table [check_operations] 
        ///go
        ///Drop table [check_point] 
        ///go
        ///Drop table [scenario] 
        ///go
        ///Drop table [section] 
        ///go
        ///Drop table [operation] 
        ///go.
        /// </summary>
        internal static string dropTables {
            get {
                return ResourceManager.GetString("dropTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert into operation(name, description) values(&apos;Operation_1&apos;, &apos;Description_1&apos;)
        ///go
        ///Insert into operation(name, description) values(&apos;Operation_2&apos;, &apos;Description_2&apos;)
        ///go
        ///Insert into operation(name, description) values(&apos;Operation_3&apos;, &apos;Description_3&apos;)
        ///go
        ///Insert into operation(name, description) values(&apos;Operation_4&apos;, &apos;Description_4&apos;)
        ///go                                    
        ///Insert into operation(name, description) values(&apos;Operation_5&apos;, &apos;Description_5&apos;)
        ///go
        ///Insert into operation(name, description) values(&apos;Op [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string fillTables {
            get {
                return ResourceManager.GetString("fillTables", resourceCulture);
            }
        }
    }
}
